export const navItems = [
  {
    name: "Home",
    href: "/dashboard",
    children: [
      "customers",
      "products",
      "projects",
      "bv-projecs",
      "employees",
      "staff",
      "locomotives",
      "settings",
      "locations",
      "wagon",
      "wagon-list",
      "track-cost",
      "wagon-history",
      "project-usn-product",
    ],
    icon: "/images/top/home.svg",
    translationKey: "home",
  },
  {
    name: "Shift Management",
    href: "/shift-management/regular-shifts/monthly",
    children: [
      "shift-management/regular-shifts/weekly",
      "shift-management/orders-shifts/monthly",
      "shift-management/orders-shifts/weekly",
      "shift-management/orders-shifts/table",
      "/shift-management/regular-shifts/add",
      "/shift-management/project-usn-shifts/add",
      "/shift-management/orders-shifts/add",
      "/shift-management/project-usn-shifts/warehouse-shifts/monthly",
      "/shift-management/project-usn-shifts/warehouse-shifts/weekly",
      "/shift-management/project-usn-shifts/usn-shifts/monthly",
      "/shift-management/project-usn-shifts/usn-shifts/weekly",
      "/shift-management/project-usn-shifts/wagon-database",
      "/shift-management/regular-shifts/trains",
    ],
    icon: "/images/top/shift-management.svg",
    translationKey: "shiftManagement",
  },
  {
    name: "Controlling",
    href: "/controlling",
    icon: "/images/top/controlling.svg",
    translationKey: "controlling",
  },
  {
    name: "Time Sheet",
    href: "/time-sheet/regular-shifts-timesheets/submitted",
    icon: "/images/top/timesheet.svg",
    children: [
      "/time-sheet/regular-shifts-timesheets/submitted",
      "/time-sheet/regular-shifts-timesheets/approved",
      "/time-sheet/regular-shifts-timesheets/rejected",
      "/time-sheet/regular-shifts-timesheets/draft",
      "/time-sheet/regular-shifts-timesheets/add",
    ],
    translationKey: "timeSheet",
  },
  {
    name: "Handover Book",
    href: "/handover-book",
    icon: "/images/top/handover-book.svg",
    children: [
      "/handover-book/regular-shifts",
      "/handover-book/orders-shifts",
      "/handover-book/project-usn-shifts",
      "/handover-book/warehouse-shifts",
    ],
    translationKey: "handoverBook",
  },
  {
    name: "Maintenance",
    href: "/maintenance/overview-of-locomotive",
    icon: "/images/top/maintenance.svg",
    translationKey: "maintenance",
    children: [
      "maintenance/overview-of-locomotive",
      "maintenance/overview-of-actions",
      "maintenance/reasons",
      "maintenance/history-of-maintenance",
    ],
  },
  {
    name: "Quality Management",
    href: "/quality-management",
    icon: "/images/top/quality-management.svg",
    translationKey: "qualityManagement",
  },
  {
    name: "Sample",
    href: "/sampling",
    icon: "/images/top/sample.svg",
    translationKey: "sample",
  },
  {
    name: "Request",
    href: "/request/receive",
    icon: "/images/top/request.svg",
    translationKey: "request",
    children: ["/request/receive", "/request/send"],
  },
];
