import type { NavLinks } from "@/types/navLinks";

export const NAV_ITEMS: NavLinks[] = [
  {
    label: "Dashboard",
    labelSmall: "Dash",
    href: "/dashboard",
    alternate: [],
    icon: "/images/bottom/dashboard.svg",
    translationKey: "dashboard",
    permissions: [],
  },
  {
    label: "Customers",
    labelSmall: "Cust",
    href: "/customers",
    alternate: ["/customers/add"],
    icon: "/images/bottom/customer.svg",
    translationKey: "customers",
    permissions: ["customer.read"],
  },
  {
    label: "Products",
    labelSmall: "Prod",
    href: "/products",
    alternate: ["/products/add"],
    icon: "/images/bottom/product.svg",
    translationKey: "products",
    permissions: ["product.read"],
  },
  {
    label: "Projects",
    labelSmall: "Proj",
    href: "/projects",
    alternate: ["/projects/add"],
    icon: "/images/bottom/projects.svg",
    translationKey: "projects",
    permissions: ["project.read"],
  },
  {
    label: "Bv Projects",
    labelSmall: "Proj",
    href: "/bv-projects",
    alternate: ["/bv-projects/add"],
    icon: "/images/bottom/bv-projects.svg",
    translationKey: "bvProjects",
    permissions: ["bv-project.read"],
  },
  {
    label: "Employees",
    labelSmall: "Empl",
    href: "/employees",
    alternate: ["/employees/add"],
    icon: "/images/bottom/employees.svg",
    translationKey: "employees",
    permissions: ["employee.read"],
  },
  {
    label: "Staff",
    labelSmall: "Staff",
    href: "/staff",
    alternate: ["/staff/add"],
    icon: "/images/bottom/staff.svg",
    translationKey: "staff",
    permissions: ["staff.read"],
  },
  {
    label: "Locomotives",
    labelSmall: "Loco",
    href: "/locomotives",
    alternate: ["/locomotives/add"],
    icon: "/images/bottom/locomotives.svg",
    translationKey: "locomotives",
    permissions: ["locomotive.read"],
  },
  {
    label: "Locations",
    labelSmall: "Loc",
    href: "/locations",
    alternate: ["/locations/add"],
    icon: "/images/bottom/locations.svg",
    translationKey: "locations",
    permissions: ["location.read"],
  },
  {
    label: "Wagon",
    labelSmall: "Wagon",
    href: "/wagon",
    alternate: ["/wagon/add"],
    icon: "/images/bottom/wagon.svg",
    translationKey: "wagon",
    permissions: ["wagon.read"],
  },
  {
    label: "WagonList",
    labelSmall: "Wagon",
    href: "/table-wagon-list",
    alternate: ["/wagon-list/add"],
    icon: "/images/bottom/wagon-list.svg",
    translationKey: "WagonList",
    permissions: ["wagon-list.read"],
  },
  {
    label: "Track Cost",
    labelSmall: "Track Cost",
    href: "/track-cost",
    alternate: ["/track-cost"],
    icon: "/images/bottom/track-cost.svg",
    translationKey: "trackcost",
    permissions: ["shift-toll-cost.read"],
  },
  {
    label: "Wagon-His",
    labelSmall: "Wagon-His",
    href: "/history-wagon",
    alternate: ["/history-wagon"],
    icon: "/images/bottom/wagon-history.svg",
    translationKey: "wegonHistory",
    permissions: ["wagon.read"],
  },
  {
    label: "Setting",
    labelSmall: "sett",
    href: "/settings/profile",
    alternate: [
      "/settings/holidays",
      "/settings/company",
      "/settings/role",
      "/settings/profile",
      "/settings/change-password",
      "/settings/type-of-operation",
      "/settings/cost-center",
    ],
    icon: "/images/setting-icon.svg",
    translationKey: "settings",
    permissions: [],
  },
];
