export type STATUS = "ACTIVE" | "ARCHIVED";

export type FORMMODE = "ADD" | "EDIT";

export type COSTING_TERMS =
  | "COUNT_HOLIDAY_SURCHARGES_COST_ONLY"
  | "COUNT_HIGHEST_SURCHARGES_COST_ONLY"
  | "COUNT_ALL_SURCHARGES_COST";
